### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by maxjf1** [tzapp/tzapp.github.io#1]
# Things that need to be done in the project:
## Databse
- [x] Convert Items DB
- [x] Convert Enemies DB
- [ ] Convert Bazaar DB
- [ ] Convert Magics DB
- [ ] Convert Technicks DB
- [ ] Convert Weapons DB
- [ ] Convert Shields DB
- [ ] Convert Head Equipment DB
- [ ] Convert Body Equipment DB
- [ ] Convert Accessories DB
- [ ] Convert Ammunition DB
- [ ] Convert Maps/Chests DB
----------
## APP
- [x] Create the base APP (react, Material UI, React Router, PWA)
- [x] Add About/Credits View
- [ ] Add state managment (redux)
- [ ] Add Items View
- [ ] Add Bazaar View
- [ ] Add Magics View
- [ ] Add Technicks View
- [ ] Add Weapons View
- [ ] Add Shields View
- [ ] Add Head Equipment View
- [ ] Add Body Equipment View
- [ ] Add Accessories View
- [ ] Add Ammunition View
- [ ] Add Maps/Chests View
- [ ] Add Enemies View

**Comment by maxjf1** [comment]
Enemies DB generated (some info may not be accurate)
